spring:
  datasource:
    dynamic:
      primary: daily
      strict: false
      grace-destroy: true
      datasource:
        daily:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/daily-news?useSSL=false&serverTimezone=UTC
          #                    url: jdbc:mysql://localhost:3306/daily-news?useSSL=false&serverTimezone=UTC
          username: root
          password: 123456
        #                    password: Admin@123
        analysis:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/financial_analytics?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
          username: root
          password: 123456
      hikari:
        max-pool-size: 40

app:
  telegram:
    token: 8291537816:AAEQTE7Jd5AGQ9dkq7NMPewlSr8Kun2qXao  # 您的机器人token
    chatId: -1002191041553
    commands:
      enabled: true
      personalized: true
      default-frequency: 30  # 默认30分钟
      max-keywords: 10
      max-news-per-push: 5

# 大额成交监听
binance:
  agg-trades:
    tg:
      token: 7800570468:AAFunJqTi_qmWH3zAy7u31TGo2wK7w0hrfc
      chatId: -1002555659999
    seconds: 10
    amt:
      ETH: 2000000
      BTC: 2000000
